posts/urls.py
from django.urls import path
from posts.views import AccountCreateView, AccountDetailView, PostsCreateView, PostsDetailView

urlpatterns = [
    path("<int:pk>/", AccountDetailView.as_view(), name="homepage"),
    path("createaccount/", AccountCreateView.as_view(), name="create_account"),
    path("createpost/", PostsCreateView.as_view(), name="create_post"),
    path("post<int:pk>/", PostsDetailView.as_view(), name="post_detail")


]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('social/', include("posts.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Account(models.Model):
    name = models.CharField(max_length=200)
    owner = models.ForeignKey(User, related_name="accounts", on_delete=models.CASCADE)
    bio = models.TextField(null=True, blank=True)
    profile_picture = models.ImageField(upload_to="profile/", blank=True, null=True)


class Posts(models.Model):
    title = models.CharField(max_length=500)
    image = models.ImageField(upload_to="imagePosts/", blank=True, null=True)
    video = models.FileField(upload_to="videoPosts/", blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    date_created = models.DateTimeField(default=timezone.now)
    poster = models.ForeignKey(User, related_name="posts", on_delete=models.CASCADE)
    account = models.ForeignKey(Account, related_name="posts", on_delete=models.CASCADE)


class UserFollowing(models.Model):
    user_id = models.ForeignKey(User, related_name="following", on_delete=models.CASCADE)
    following_user_id = models.ForeignKey(User, related_name="followers", on_delete=models.CASCADE)

accounts/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.models import Account, Posts, UserFollowing
# Create your views here.

#I need a view to create the account "home" page
class AccountCreateView(CreateView):
    model = Account
    template_name = "posts/createAccount.html"
    fields = ["name", "profile_picture", "bio"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("homepage")


#I need a view to show my account details and list my posts
class AccountDetailView(DetailView):
    model = Account
    template_name = "posts/list.html"
    context_object_name = "accountdetail"

    


#I need a view to create Posts
class PostsCreateView(CreateView):
    model = Posts
    template_name = "posts/createPost.html"
    fields = ["title", "image", "video", "description", "date_created"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.poster = self.request.user
        item.account = self.request.user.accounts
        item.save()
        return redirect("homepage")


class PostsDetailView(DetailView):
    model = Posts
    template_name = "posts/postDetail.html"
    context_object_name = "postdetail"

posts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <style>
    body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
    .w3-third img{margin-bottom: -6px; opacity: 0.8; cursor: pointer}
    .w3-third img:hover{opacity: 1}
    </style>
</head>
<body>
    <header class="w3-container w3-top w3-hide-large w3-white w3-xlarge w3-padding-16">
            <span class="w3-left w3-padding">SOME NAME</span>
            <a href="javascript:void(0)" class="w3-right w3-button w3-white" onclick="w3_open()">☰</a>
        <nav>
            {% comment %} <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    <li><a href="{% url 'create_receipt' %}">Create Receipt</a></li>
                    <li><a href="{% url 'expense_category' %}">Expense Categories</a></li>
                    <li><a href="{% url 'create_category' %}">Create Expense Category</a></li>
                    <li><a href="{% url 'account_list' %}">Accounts</a></li>
                    <li><a href="{% url 'create_account' %}">Create Account</a></li>
                {% endif %}
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'signup' %}">Signup</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul> {% endcomment %}
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
<body>


</html>

posts/templates/posts/createAccount.html
{% extends "../base.html" %} 
{% block content %}

<div>
    <h1>Create Account</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button" >Create</button>
    </form>
</div>

{% endblock content %}

posts/templates/posts/list.html
{% extends "../base.html" %}
{% block content %}

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:650px">

  <!-- Push down content on small screens --> 
  <div class="w3-hide-large" style="margin-top:100px"></div>
 
<div class="topinfo">
<h1>{{ accountdetail.name }}</h1>
<img src="{{ accountdetail.profile_picture.url }}" width="200" height="200">
<br>
<br>
{{ accountdetail.bio }}
<br>
<br>
</div>
<!-- Photo Grid -->
<div class="w3-row">
    <div class="wrapper">
        {% for object in accountdetail.posts.all %}
          <div><img src="{{ object.image.url }}" width="300" height="400" onclick="onClick(this)" alt="{{ object.title }}<br>{{ object.description }}<br>{{ object.date_created }}"></div>
        {% endfor %}    
    </div>
</div>
  <!-- Pagination -->
   <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a href="#" class="w3-bar-item w3-button w3-hover-black">«</a>
      <a href="#" class="w3-bar-item w3-black w3-button">1</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">2</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">3</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">4</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">»</a>
    </div>
  </div>     
</div>
<!-- Modal for full size images on click-->
<div id="modal01" class="w3-modal w3-black" style="padding-top:0" onclick="this.style.display='none'">
  <span class="w3-button w3-black w3-xlarge w3-display-topright">×</span>
  <div class="w3-modal-content w3-animate-zoom w3-center w3-transparent w3-padding-64">
    <img id="img01" class="w3-image">
    <p id="caption"></p>
  </div>
</div>
<script>
    // Script to open and close sidebar
    function w3_open() {
      document.getElementById("mySidebar").style.display = "block";
      document.getElementById("myOverlay").style.display = "block";
    }
     
    function w3_close() {
      document.getElementById("mySidebar").style.display = "none";
      document.getElementById("myOverlay").style.display = "none";
    }
    
    // Modal Image Gallery
    function onClick(element) {
      document.getElementById("img01").src = element.src;
      document.getElementById("modal01").style.display = "block";
      var captionText = document.getElementById("caption");
      captionText.innerHTML = element.alt;
    }
    
    </script>
{% endblock %}